### ISSUE TITLE
the link to the live site is wrong

### ISSUE THREAD

**Issue by EMCain** [ArtOfCode-/SCOT#114]
I don't think I can change this with a commit. The description of the repo on Github goes to  https://scot.artofcode.co.uk/ - it should go to https://scot.crowdrescuehq.org/ .

**Comment by ArtOfCode-** [comment]
I'm no longer involved with CRHQ, which is why this repo doesn't link to the CRHQ live version. https://scot.artofcode.co.uk is dead, though, so I'll remove that.

**Comment by thesecretmaster** [comment]
@ArtOfCode Can you transfer the repo to me then, since I hope to keep working on it?

**Comment by artofcode** [comment]
@ArtOfCode- , not @artofcode :)

**Comment by thesecretmaster** [comment]
Sorry! Hyphens are hard.

**Comment by ArtOfCode-** [comment]
@artofcode I'm sure that's the second time someone's done that to you... Sorry :D

**Comment by ArtOfCode-** [comment]
@izwick-schachter Negative. SCOT is still something I work on, too, so it may as well stay here. You've still got, and will keep, push access.
