### ISSUE TITLE
Resource Tracking

### ISSUE THREAD

**Issue by izwick-schachter** [ArtOfCode-/SCOT#4]
We should add a section to track various resources that could be useful to victims of disasters, for example shelter, food sources, etc. This is _fairly_ low priority because fulcrum already does this well enough, and there's not a whole lot of room to improve.

**Comment by izwick-schachter** [comment]
Now it's done by ERSI and that map. Really, any tooling around this can't be improved so there's no reason to do this within SCOT.

**Comment by ArtOfCode-** [comment]
I disagree there. Reopening for now, we can discuss details in a few hours.

**Comment by ArtOfCode-** [comment]
In a similar vein to this - or perhaps using the same models and data - we should build a live dispatch system.

**Comment by ArtOfCode-** [comment]
Done by CAD
