### ISSUE TITLE
New ticker/Announcement area

### ISSUE THREAD

**Issue by izwick-schachter** [ArtOfCode-/SCOT#65]
There should be an area to put related disaster links one of which is Breaking News, The Breaking News may be a ticker to be displayed per settings.

**Comment by MeghanUX** [comment]
Hi all. Not sure if this is the correct place.

For any items originally entered under category "Breaking News", can we do the following:
1. Display them in a special section in the generated Broadcast script. Below Script title. Below "Intro". Above "General News".
2. Date-stamp them. Stop displaying them by EOD (after last broadcast for the day)
3. After their one-day appearance, change their category to "General News" and display them in the General News section of the generate broadcast script, BUT - also add this text:
  "Originally from "Breaking News" on [date]" <-- use a dark gray and/or italics font. Uneditable.

This approach limits their display as "Breaking News" to ONE day. Keeps them in the system (though under a different category, same ID) and allows the broadcasters to decide whether or not to keep the item.

Thanks!

**Comment by ArtOfCode-** [comment]
Notifications do this
